import { GuitarProduct } from "./types";

export const guitar: GuitarProduct[] = [
  {
    image: "guitarcard.jpeg",
    brand: "Yamaha",
    title: "Guitar",
    price: 120,
    discountedPrice: 50,
    discountPercent: 60,
    category: "guitar",
    description: "A Yamaha guitar",
    quantity: 100,
    topLevelCategory: "Instuments",
    secondLevelCategory: "Guitar",
    thirdLevelCategory: "Acoustic",
  },
  {
    image: "guitarcard.jpeg",
    brand: "Yamaha",
    title: "Guitar",
    price: 12000,
    discountedPrice: 5000,
    discountPercent: 60,
    category: "guitar",
    description: " A Yamaha guitar",
    quantity: 100,
    topLevelCategory: "Instuments",
    secondLevelCategory: "Guitar",
    thirdLevelCategory: "Acoustic",
  },
  {
    image: "guitarcard.jpeg",
    brand: "Yamaha",
    title: "Guitar",
    price: 12000,
    discountedPrice: 5000,
    discountPercent: 60,
    category: "guitar",
    description: " A Yamaha guitar",
    quantity: 100,
    topLevelCategory: "Instuments",
    secondLevelCategory: "Guitar",
    thirdLevelCategory: "Acoustic",
  },
  {
    image: "guitarcard.jpeg",
    brand: "Yamaha",
    title: "Guitar",
    price: 12000,
    discountedPrice: 5000,
    discountPercent: 60,
    category: "guitar",
    description: " A Yamaha guitar",
    quantity: 100,
    topLevelCategory: "Instuments",
    secondLevelCategory: "Guitar",
    thirdLevelCategory: "Acoustic",
  },
  {
    image: "guitarcard.jpeg",
    brand: "Yamaha",
    title: "Guitar",
    price: 12000,
    discountedPrice: 5000,
    discountPercent: 60,
    category: "guitar",
    description: " A Yamaha guitar",
    quantity: 100,
    topLevelCategory: "Instuments",
    secondLevelCategory: "Guitar",
    thirdLevelCategory: "Acoustic",
  },
  {
    image: "guitarcard.jpeg",
    brand: "Yamaha",
    title: "Guitar",
    price: 12000,
    discountedPrice: 5000,
    discountPercent: 60,
    category: "guitar",
    description: " A Yamaha guitar",
    quantity: 100,
    topLevelCategory: "Instuments",
    secondLevelCategory: "Guitar",
    thirdLevelCategory: "Acoustic",
  },
  {
    image: "guitarcard.jpeg",
    brand: "Yamaha",
    title: "Guitar",
    price: 12000,
    discountedPrice: 5000,
    discountPercent: 60,
    category: "guitar",
    description: " A Yamaha guitar",
    quantity: 100,
    topLevelCategory: "Instuments",
    secondLevelCategory: "Guitar",
    thirdLevelCategory: "Acoustic",
  },
  {
    image: "guitarcard.jpeg",
    brand: "Yamaha",
    title: "Guitar",
    price: 12000,
    discountedPrice: 5000,
    discountPercent: 60,
    category: "guitar",
    description: " A Yamaha guitar",
    quantity: 100,
    topLevelCategory: "Instuments",
    secondLevelCategory: "Guitar",
    thirdLevelCategory: "Acoustic",
  },
  {
    image: "guitarcard.jpeg",
    brand: "Yamaha",
    title: "Guitar",
    price: 12000,
    discountedPrice: 5000,
    discountPercent: 60,
    category: "guitar",
    description: " A Yamaha guitar",
    quantity: 100,
    topLevelCategory: "Instuments",
    secondLevelCategory: "Guitar",
    thirdLevelCategory: "Acoustic",
  },
];
